// Saga
export const FETCH_REPOS_SAGA = 'FRONT/FETCH_REPOS';
export const FETCH_SINGLE_REPO_SAGA = 'FRONT/FETCH_SINGLE_REPO';
// Action
export const INSERT_REPOS_ACTION = 'FRONT/INSERT_REPOS';
export const RESET_REPOS_ACTION = 'FRONT/RESET_REPOS';

export const GIT_NAMESPACE = 'github';