// Saga
export const FETCH_REPOS_SAGA = 'FRONT/FETCH_REPOS';
export const FETCH_SINGLE_REPO_SAGA = 'FRONT/FETCH_SINGLE_REPO';
export const FETCH_REPO_CONTENT_SAGA = 'FRONT/FETCH_REPO_CONTENT';
// Action
export const INSERT_REPOS_ACTION = 'FRONT/INSERT_REPOS';
export const INSERT_SINGLE_REPOS_ACTION = 'FRONT/INSERT_SINGLE_REPOS';
export const FETCH_REPO_CONTENT_ACTION = 'FRONT/INSERT_REPO_CONTENT';
export const RESET_REPOS_ACTION = 'FRONT/RESET_REPOS';

export const GIT_NAMESPACE = 'github';